apiVersion: v1
kind: Secret
metadata:
  name: talentflow-secrets
  namespace: talentflow
type: Opaque
stringData:
  mysql-root-password: "password"
  openai-api-key: "sk-bd92be268fa04ea9a6803ed3d6b7f28d"
  jwt-secret-key: "super-secret-key-change-in-prod"
