apiVersion: v1
kind: ConfigMap
metadata:
  name: talentflow-config
  namespace: talentflow
data:
  mysql-server: "mysql"
  mysql-user: "root"
  mysql-database: "talentflow_db"
  redis-url: "redis://redis:6379"
  backend-host: "backend"
